In [37]:
import numpy as np

def ordered_array(j, k):
    array = np.array([[m + (k*n) for m in range(k)] for n in range(j)])
    print('Array Original :\n', array, end='\n\n')
    return array


def random_array(j, k):
    array = np.random.randint(0, 100, (j, k))
    print('Array Original :\n', array, end='\n\n')
    return array

Exercício 1: Crie um array de 10 elementos. Depois, altere os valores de todos os
elementos com índices de 5 a 8 para 0.

In [38]:
a = np.array([i for i in range(10)])
print('Array Original :\n', a, end='\n\n')

a[5:8] = 0
print('Array Modificado:\n', a)

Array Original :
 [0 1 2 3 4 5 6 7 8 9]

Array Modificado:
 [0 1 2 3 4 0 0 0 8 9]


Exercício 2: Crie um array com 3 linhas e 2 colunas. Depois imprima o shape e a 2ª
linha da matriz.

In [39]:
a = ordered_array(3, 2)
print('Shape: ', np.shape(a))
print('2ª Linha:\n', a[1])

Array Original :
 [[0 1]
 [2 3]
 [4 5]]

Shape:  (3, 2)
2ª Linha:
 [2 3]


Exercício 3: Crie um array com 3 linhas e 2 colunas. Depois imprima a 2ª coluna.

In [40]:
a = ordered_array(3, 2)
print('2ª Coluna:\n', a[:,1])

Array Original :
 [[0 1]
 [2 3]
 [4 5]]

2ª Coluna:
 [1 3 5]


Exercício 4: Crie um array de com 4 linhas e 5 colunas. Depois imprima os elementos
da terceira linha da matriz.

In [41]:
a = ordered_array(4, 5)
print('3ª Linha:\n', a[2])

Array Original :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

3ª Linha:
 [10 11 12 13 14]


Exercício 5: Crie um array de com 4 linhas e 5 colunas. Depois imprima todos os
elementos da primeira e segunda linhas e segunda a terceira colunas.

In [42]:
a = ordered_array(4, 5)
print('1ª e 2ª Linhas, 2ª e 3ª Colunas:\n', a[0:2, 1:3])

Array Original :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

1ª e 2ª Linhas, 2ª e 3ª Colunas:
 [[1 2]
 [6 7]]


Exercício 6: Crie um array de com 4 linhas e 5 colunas. Depois imprima todos os
elementos da segunda e terceira linhas e primeira a terceira colunas.

In [43]:
a = ordered_array(4, 5)
print('2ª e 3ª Linhas, 1ª a 3ª Colunas:\n',a[1:3, 0:3])

Array Original :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

2ª e 3ª Linhas, 1ª a 3ª Colunas:
 [[ 5  6  7]
 [10 11 12]]
