In [ ]:
import numpy as np

Exercício 1: Crie um array de 10 elementos. Depois, altere os valores de todos os
elementos com índices de 5 a 8 para 0.

In [12]:
a = np.array([i for i in range(10)])
a[5:8] = 0
print(a)

[0 1 2 3 4 0 0 0 8 9]


Exercício 2: Crie um array com 3 linhas e 2 colunas. Depois imprima o shape e a 2ª
linha da matriz.

In [13]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(np.shape(a))
print(a[1])

(3, 2)
[3 4]


Exercício 3: Crie um array com 3 linhas e 2 colunas. Depois imprima a 2ª coluna.

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[:,1])

[2 4 6]


Exercício 4: Crie um array de com 4 linhas e 5 colunas. Depois imprima os elementos
da terceira linha da matriz.

In [11]:
a = np.array([[i + (5*j) for i in range(5)] for j in range(4)])
print(a[2])

[10 11 12 13 14]


Exercício 5: Crie um array de com 4 linhas e 5 colunas. Depois imprima todos os
elementos da primeira e segunda linhas e segunda a terceira colunas.

In [20]:
a = np.array([[i + (5*j) for i in range(5)] for j in range(4)])
print(a[0:2, 1:3])

[[1 2]
 [6 7]]


Exercício 6: Crie um array de com 4 linhas e 5 colunas. Depois imprima todos os
elementos da segunda e terceira linhas e primeira a terceira colunas.

In [18]:
a = np.array([[i + (5*j) for i in range(5)] for j in range(4)])
print(a[1:3, 0:3])

[[ 5  6  7]
 [10 11 12]]
